// Needs to be tested first.
await import(`./test_test.mjs`)
await import(`./lang_test.mjs`)

await import(`./coll_test.mjs`)
await import(`./arr_test.mjs`)
await import(`./http_test.mjs`)
await import(`./http_shared_test.mjs`)
await import(`./iter_test.mjs`)
await import(`./obj_test.mjs`)
await import(`./obs_test.mjs`)
await import(`./str_test.mjs`)
await import(`./time_test.mjs`)
await import(`./url_test.mjs`)
await import(`./path_test.mjs`)
await import(`./dom_reg_test.mjs`)
await import(`./dom_shim_test.mjs`)
await import(`./prax_test.mjs`)
await import(`./cli_test.mjs`)

if (import.meta.main) console.log(`[test] ok!`)
